apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: demo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      labels:
        app: demo-shop
    spec:
      containers:
        - name: user-service-container
          image: user-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root1234
            - name: MYSQL_URL
              value: jdbc:mysql://demo-shop.c9pmrkdcjaav.eu-central-1.rds.amazonaws.com/users_db
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: demo-shop
  ports:
    - port: 8082
      targetPort: 8082
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: rds-svc
spec:
  clusterIP: None
  ports:
    - port: 3306

---

kind: Endpoints
apiVersion: v1
metadata:
  name: rds-svc
subsets:
  - addresses:
      - ip: 18.192.254.230
    ports:
      - port: 3306
        name: rds-svc


